Adding control properties API
erickzanardo/dashbook pull request #49
Opened 2021-04-20 18:27 UTC by erickzanardo

This PR adds the control properties API.

https://user-images.githubusercontent.com/835641/115445969-eb7b1d00-a1ec-11eb-8f32-2ef8bdf04b71.mov

2021-04-20 19:00 UTC, tyemy approved these changes

2021-04-21 17:16 UTC, jeffs-sf requested changes
As the author of #47 this does exactly what I was looking for, thank you! There's some room for expansion later (maybe hiding if it doesn't match the type verses including if it does), but this helps tremendously.

There's one missing property that doesn't currently respect the `ControlProperty` but allows the consumer to define it (`TextProperty`) and some minor grammar suggestions. I added support for it locally to verify that passing in that `ControlProperty` to the `Property` works.

2021-04-21 17:16 UTC, jeffs-sf commented on example/lib/widgets/message_card.dart
> +class MessageCard extends StatelessWidget {
**suggestion:**
```suggestion
/// Naive widget to be an example of a little bit more
/// complex one with different types.
class MessageCard extends StatelessWidget {
```

2021-04-21 17:16 UTC, jeffs-sf commented on lib/src/widgets/properties_container.dart
> +    for (var entry in widget.currentChapter.ctx.properties.entries) {
**suggestion:** we could break this out into a method

2021-04-21 17:16 UTC, jeffs-sf commented on lib/src/story.dart
> +      {ControlProperty? controlProperty}) {
**chore (blocking):** we need to utilize the `controlProperty` here and pass it to the `Property` like we added for the other property types.
https://github.com/erickzanardo/dashbook/blob/0de95e01ae6898d27deb4e5f0b7fedcae763fad1/lib/src/story.dart#L33-L34

```dart
      final property = Property<String>(name, defaultValue,
          controlProperty: controlProperty);
      properties[name] = property;
```

2021-04-21 17:39 UTC, erickzanardo commented
Thanks for the review @tyemy and @jeffs-sf I have applied the suggestions.

2021-04-21 17:40 UTC, merged